version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:16.10.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
            - run:
                  name: Install dependencies
                  command: yarn install --production=false --cache-folder ~/.cache/yarn
            - save_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
                      - ~/.cache/yarn
            - run:
                  name: Build project
                  command: yarn build
